<?php

/**
* NeuraFrame is a mini PHP framework for creating MVC applications
*
* @author Dusan Djordjevic <theneura@gmail.com>
*/

/**
* Require a autoloader generated by composer
*/
require __DIR__. '/../NeuraFrameApplication/bootstrap/autoload.php';

/**
* Require NeuraFrame application
*/

require __DIR__. '/../NeuraFrameApplication/bootstrap/app.php';